### ISSUE TITLE
Added Entries not appearing in the list

### ISSUE THREAD

**Issue by RChiodo0610** [meienberger/nextgba#2]
Hello, I have a few ROMs that I uploaded and have not appeared in the list, and if I attempt to reupload them, I am notified that the game has already been added. If I change the name slightly to upload the rom under a new name, I see the notification that the game was added, but the list does not reflect this. 

If I navigate to the folder where the games are held /nextgba/data/games/ the files are in the directory.

I have tried clearing my cache and using different devices and browsers.

**Comment by RChiodo0610** [comment]
Ended up running EmulatorJS

**Comment by six-shooter** [comment]
I am having the same issue,
I am running the RunTipi version (which runs on proxmox)
